import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/sidebar'
import MobileSidebar from '@/components/mobile-sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: "/asset/favicon.ico",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="hidden md:flex h-full w-64 flex-col fixed inset-y-0 z-50">
      <Sidebar />
      </div>
      <div className='md:hidden  '>
        <MobileSidebar />
      </div>
      <div className='md:pl-72 py-6'>
        {children}
      </div>
        </body>
    </html>
  )
}
